# Generated by Django 4.2.2 on 2023-06-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('socio', models.BooleanField()),
                ('telefono', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_cantidad', models.IntegerField()),
                ('venta_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.cliente')),
                ('venta_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.empleado')),
                ('venta_factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.factura')),
                ('venta_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Provee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.producto')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_shell.proveedor')),
            ],
        ),
    ]
